export const MARGIN_BOTTOM_RATIO = 0.05;
export const BIG_CIRCLE_RADIUS = 6;
export const SMALLER_CIRCLE_RADIUS = BIG_CIRCLE_RADIUS * 0.6;
export const SVG_HEIGHT_RATIO = 0.9;
export const UNIT_INTERVALS_AMOUNT = 100;